### ISSUE TITLE
svelte(missing-declaration)

### ISSUE THREAD

**Issue by el3um4s** [fuzzc0re/electron-svelte-typescript#6] opened 2021-06-23 12:37 UTC
I have created a **Test.svelte** component

```
<script lang="ts">
    export let hello:string = "World"
</script>

<div>{hello}</div>
```

I have this worning in VScode

![image](https://user-images.githubusercontent.com/23579630/123097020-00b03a00-d430-11eb-976c-1f93d9fd1933.png)

Then I imported the component into App.svelte

```
<script lang="ts">
  import Test from "./Test.svelte";
  export let name: string;
</script>

<main>
  <h1>Hello {name}!</h1>
  <p>Visit the <a href="https://svelte.dev/tutorial">Svelte tutorial</a> to learn how to build Svelte apps.</p>
  <Test />
</main>
```

I have this worning in VScode

![image](https://user-images.githubusercontent.com/23579630/123096930-e6765c00-d42f-11eb-9bb0-7b05b61a6334.png)

By searching I found this hypothesis for a solution

[Getting svelte(missing-declaration) warnings for props](https://github.com/sveltejs/language-tools/issues/826#issuecomment-783077899)

But I don't know how to do it.

**Comment by SilentEchoUK** [comment] 2021-09-27 17:50
Accidentally fixed this while resolving a path aliasing problem that had the same root cause so submitted a pull request that appears to solve it without affecting anything else by juist shuffling the config files around

**Comment by fuzzc0re** [comment] 2021-09-28 07:48
Thanks for the help @SilentEchoUK 
Closing the issue due to 7aee0f9

**Closed** 2021-09-28 07:49 UTC
